name: cd

on:
  push:
    branches: [main]

jobs: # <-- Fix indentation here
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build the app
        run: scripts/buildprod.sh
